"""SailPoint IdentityIQ request generation (Phase 11 / Section 17).

There is no SailPoint environment attached to this MVP, and this service does
not pretend otherwise: it builds the request payload an IdentityIQ connector
would submit, marks it `SIMULATED`, and persists it. Nothing is sent anywhere.

`submit_request()` is the seam a real connector drops into later. It exists as
an explicit `NotImplementedError` rather than a stub that returns a fake
success, because a stub that lies about provisioning is worse than no stub.

Only entitlements whose decision satisfies the configured approval criteria are
included. Blocked, rejected, review-pending and not-recommended entitlements
are listed separately under `excluded_entitlements` so the exclusion itself is
auditable rather than invisible.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from app.config import Settings, get_settings
from app.domain.enums import RecommendationStatus, SailPointRequestStatus
from app.domain.models import (
    AccessDecision,
    EmployeeProfile,
    SailPointRequestedEntitlement,
    SailPointRequestPayload,
)
from app.logging import get_logger

logger = get_logger(__name__)


class SailPointService:
    """Generates IdentityIQ-style access-request payloads."""

    def __init__(self, settings: Settings | None = None) -> None:
        self.settings = settings or get_settings()

    @property
    def included_statuses(self) -> set[RecommendationStatus]:
        statuses: set[RecommendationStatus] = set()
        for raw in self.settings.sailpoint_included_statuses:
            try:
                statuses.add(RecommendationStatus(raw))
            except ValueError:
                logger.warning("sailpoint.unknown_status_in_config", value=raw)
        return statuses

    def generate_request_payload(
        self,
        *,
        employee: EmployeeProfile,
        decisions: list[AccessDecision],
        analysis_id: str | None = None,
        correlation_id: str | None = None,
    ) -> SailPointRequestPayload:
        eligible = self.included_statuses
        included: list[SailPointRequestedEntitlement] = []
        excluded: list[dict[str, Any]] = []

        for decision in decisions:
            if decision.recommendation_status in eligible:
                included.append(
                    SailPointRequestedEntitlement(
                        application=decision.application,
                        entitlement=decision.entitlement_id,
                        entitlement_name=decision.entitlement_name,
                        approval_tier=decision.approval_tier,
                        risk_level=decision.risk_level,
                        affinity_score=decision.affinity_score,
                    )
                )
            else:
                excluded.append(
                    {
                        "application": decision.application,
                        "entitlement": decision.entitlement_id,
                        "recommendation_status": decision.recommendation_status.value,
                        "reason": decision.reason,
                    }
                )

        included.sort(key=lambda e: (e.application, e.entitlement))

        justification = (
            f"Onboarding access for {employee.name} ({employee.employee_id}), "
            f"{employee.job_role} in {employee.department}. Recommended based on peer analysis "
            f"and validated by risk, policy and segregation-of-duties controls. "
            f"{len(included)} entitlement(s) met the approval criteria; "
            f"{len(excluded)} were withheld."
        )

        payload = SailPointRequestPayload(
            identity=employee.employee_id,
            request_type=self.settings.sailpoint_request_type,
            requested_entitlements=included,
            justification=justification,
            source=self.settings.sailpoint_source_name,
            status=SailPointRequestStatus.SIMULATED.value,
            generated_at=datetime.now(timezone.utc),
            metadata={
                "analysis_id": analysis_id,
                "correlation_id": correlation_id,
                "identity_name": employee.name,
                "department": employee.department,
                "job_role": employee.job_role,
                "job_level": employee.job_level,
                "location": employee.location,
                "manager_id": employee.manager_id,
                "included_statuses": sorted(s.value for s in eligible),
                "simulated": True,
                "note": (
                    "Generated by the Agentic Access Recommendation Engine. No SailPoint "
                    "environment was contacted; this payload has not been provisioned."
                ),
            },
            excluded_entitlements=excluded,
        )

        logger.info(
            "sailpoint.payload_generated",
            employee_id=employee.employee_id,
            analysis_id=analysis_id,
            included=len(included),
            excluded=len(excluded),
            status=payload.status,
        )
        return payload

    def submit_request(self, payload: SailPointRequestPayload) -> None:
        """Reserved for a real IdentityIQ connector.

        A future implementation authenticates against IdentityIQ and POSTs the
        payload to the access-request API. It is deliberately unimplemented:
        this MVP has no SailPoint environment and must not imply that a request
        was provisioned.
        """
        raise NotImplementedError(
            "Submission to SailPoint is not implemented in this MVP. The payload is generated "
            "and persisted with status SIMULATED; wire a real IdentityIQ connector here."
        )
