"""initial schema

Revision ID: 311d65e109de
Revises: 
Create Date: 2026-08-12 00:44:24.050385
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '311d65e109de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('employee_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=128), nullable=False),
    sa.Column('job_role', sa.String(length=128), nullable=False),
    sa.Column('job_level', sa.String(length=32), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('manager_id', sa.String(length=64), nullable=True),
    sa.Column('cost_center', sa.String(length=64), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('employment_status', sa.String(length=32), nullable=False),
    sa.Column('employment_type', sa.String(length=32), server_default='EMPLOYEE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.employee_id'], name=op.f('fk_employees_manager_id_employees'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('employee_id', name=op.f('pk_employees'))
    )
    op.create_index('ix_employees_employment_status', 'employees', ['employment_status'], unique=False)
    op.create_index('ix_employees_peer_match', 'employees', ['department', 'job_role', 'job_level'], unique=False)
    op.create_table('entitlements',
    sa.Column('entitlement_id', sa.String(length=64), nullable=False),
    sa.Column('entitlement_name', sa.String(length=200), nullable=False),
    sa.Column('application', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_category', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('entitlement_id', name=op.f('pk_entitlements'))
    )
    op.create_index('ix_entitlements_application', 'entitlements', ['application'], unique=False)
    op.create_table('policies',
    sa.Column('policy_id', sa.String(length=64), nullable=False),
    sa.Column('policy_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('policy_type', sa.String(length=64), nullable=False),
    sa.Column('rule_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('policy_id', name=op.f('pk_policies'))
    )
    op.create_index('ix_policies_enabled', 'policies', ['enabled'], unique=False)
    op.create_table('employee_entitlements',
    sa.Column('employee_id', sa.String(length=64), nullable=False),
    sa.Column('entitlement_id', sa.String(length=64), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=64), server_default='SEED', nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name=op.f('fk_employee_entitlements_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entitlement_id'], ['entitlements.entitlement_id'], name=op.f('fk_employee_entitlements_entitlement_id_entitlements'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('employee_id', 'entitlement_id', name=op.f('pk_employee_entitlements'))
    )
    op.create_index('ix_employee_entitlements_entitlement_id', 'employee_entitlements', ['entitlement_id'], unique=False)
    op.create_table('joiner_analyses',
    sa.Column('analysis_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('employee_id', sa.String(length=64), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('matching_strategy', sa.String(length=64), nullable=True),
    sa.Column('strategies_attempted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('peer_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('peer_count', sa.Integer(), nullable=False),
    sa.Column('peer_confidence', sa.Float(), nullable=True),
    sa.Column('affinity_threshold', sa.Float(), nullable=True),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name=op.f('fk_joiner_analyses_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('analysis_id', name=op.f('pk_joiner_analyses'))
    )
    op.create_index('ix_joiner_analyses_employee_id', 'joiner_analyses', ['employee_id'], unique=False)
    op.create_index('ix_joiner_analyses_status', 'joiner_analyses', ['status'], unique=False)
    op.create_table('sod_rules',
    sa.Column('sod_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('entitlement_1', sa.String(length=64), nullable=False),
    sa.Column('entitlement_2', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entitlement_1'], ['entitlements.entitlement_id'], name=op.f('fk_sod_rules_entitlement_1_entitlements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entitlement_2'], ['entitlements.entitlement_id'], name=op.f('fk_sod_rules_entitlement_2_entitlements'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sod_id', name=op.f('pk_sod_rules'))
    )
    op.create_index('ix_sod_rules_enabled', 'sod_rules', ['enabled'], unique=False)
    op.create_index('ix_sod_rules_entitlement_1', 'sod_rules', ['entitlement_1'], unique=False)
    op.create_index('ix_sod_rules_entitlement_2', 'sod_rules', ['entitlement_2'], unique=False)
    op.create_table('recommendations',
    sa.Column('recommendation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('analysis_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('employee_id', sa.String(length=64), nullable=False),
    sa.Column('entitlement_id', sa.String(length=64), nullable=False),
    sa.Column('affinity_score', sa.Float(), nullable=False),
    sa.Column('peer_count', sa.Integer(), nullable=False),
    sa.Column('total_peers', sa.Integer(), nullable=False),
    sa.Column('affinity_threshold', sa.Float(), nullable=False),
    sa.Column('matching_strategy', sa.String(length=64), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('policy_status', sa.String(length=32), nullable=False),
    sa.Column('sod_status', sa.String(length=32), nullable=False),
    sa.Column('sod_severity', sa.String(length=32), nullable=True),
    sa.Column('recommendation_status', sa.String(length=32), nullable=False),
    sa.Column('approval_tier', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('decision_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['joiner_analyses.analysis_id'], name=op.f('fk_recommendations_analysis_id_joiner_analyses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name=op.f('fk_recommendations_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entitlement_id'], ['entitlements.entitlement_id'], name=op.f('fk_recommendations_entitlement_id_entitlements'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recommendation_id', name=op.f('pk_recommendations')),
    sa.UniqueConstraint('analysis_id', 'entitlement_id', name='uq_recommendation_per_analysis')
    )
    op.create_index('ix_recommendations_analysis_id', 'recommendations', ['analysis_id'], unique=False)
    op.create_index('ix_recommendations_status', 'recommendations', ['recommendation_status'], unique=False)
    op.create_table('sailpoint_requests',
    sa.Column('request_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('analysis_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('employee_id', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('entitlement_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['joiner_analyses.analysis_id'], name=op.f('fk_sailpoint_requests_analysis_id_joiner_analyses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name=op.f('fk_sailpoint_requests_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id', name=op.f('pk_sailpoint_requests'))
    )
    op.create_index('ix_sailpoint_requests_analysis_id', 'sailpoint_requests', ['analysis_id'], unique=False)
    op.create_index('ix_sailpoint_requests_employee_id', 'sailpoint_requests', ['employee_id'], unique=False)
    op.create_table('policy_results',
    sa.Column('result_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('recommendation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('policy_id', sa.String(length=64), nullable=False),
    sa.Column('policy_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('approval_tier', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.recommendation_id'], name=op.f('fk_policy_results_recommendation_id_recommendations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('result_id', name=op.f('pk_policy_results'))
    )
    op.create_index('ix_policy_results_rec_id', 'policy_results', ['recommendation_id'], unique=False)
    op.create_table('recommendation_evidence',
    sa.Column('evidence_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('recommendation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('peer_employee_id', sa.String(length=64), nullable=True),
    sa.Column('entitlement_id', sa.String(length=64), nullable=False),
    sa.Column('evidence_type', sa.String(length=64), nullable=False),
    sa.Column('evidence_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.recommendation_id'], name=op.f('fk_recommendation_evidence_recommendation_id_recommendations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evidence_id', name=op.f('pk_recommendation_evidence'))
    )
    op.create_index('ix_recommendation_evidence_rec_id', 'recommendation_evidence', ['recommendation_id'], unique=False)
    op.create_table('recommendation_explanations',
    sa.Column('explanation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('recommendation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('structured_explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('generator', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.recommendation_id'], name=op.f('fk_recommendation_explanations_recommendation_id_recommendations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('explanation_id', name=op.f('pk_recommendation_explanations')),
    sa.UniqueConstraint('recommendation_id', name=op.f('uq_recommendation_explanations_recommendation_id'))
    )
    op.create_table('sod_results',
    sa.Column('result_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('recommendation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sod_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('conflicting_entitlement_id', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.recommendation_id'], name=op.f('fk_sod_results_recommendation_id_recommendations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('result_id', name=op.f('pk_sod_results'))
    )
    op.create_index('ix_sod_results_rec_id', 'sod_results', ['recommendation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sod_results_rec_id', table_name='sod_results')
    op.drop_table('sod_results')
    op.drop_table('recommendation_explanations')
    op.drop_index('ix_recommendation_evidence_rec_id', table_name='recommendation_evidence')
    op.drop_table('recommendation_evidence')
    op.drop_index('ix_policy_results_rec_id', table_name='policy_results')
    op.drop_table('policy_results')
    op.drop_index('ix_sailpoint_requests_employee_id', table_name='sailpoint_requests')
    op.drop_index('ix_sailpoint_requests_analysis_id', table_name='sailpoint_requests')
    op.drop_table('sailpoint_requests')
    op.drop_index('ix_recommendations_status', table_name='recommendations')
    op.drop_index('ix_recommendations_analysis_id', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index('ix_sod_rules_entitlement_2', table_name='sod_rules')
    op.drop_index('ix_sod_rules_entitlement_1', table_name='sod_rules')
    op.drop_index('ix_sod_rules_enabled', table_name='sod_rules')
    op.drop_table('sod_rules')
    op.drop_index('ix_joiner_analyses_status', table_name='joiner_analyses')
    op.drop_index('ix_joiner_analyses_employee_id', table_name='joiner_analyses')
    op.drop_table('joiner_analyses')
    op.drop_index('ix_employee_entitlements_entitlement_id', table_name='employee_entitlements')
    op.drop_table('employee_entitlements')
    op.drop_index('ix_policies_enabled', table_name='policies')
    op.drop_table('policies')
    op.drop_index('ix_entitlements_application', table_name='entitlements')
    op.drop_table('entitlements')
    op.drop_index('ix_employees_peer_match', table_name='employees')
    op.drop_index('ix_employees_employment_status', table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
