"""add employees.manager_external_id for source-system manager routing

Revision ID: 5b712a58eba3
Revises: db9bff315424
Create Date: 2026-08-12 23:30:14.714397
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5b712a58eba3'
down_revision: Union[str, None] = 'db9bff315424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('manager_external_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'manager_external_id')
    # ### end Alembic commands ###
