"""add entitlements.external_id for source-system traceability

Revision ID: db9bff315424
Revises: 311d65e109de
Create Date: 2026-08-12 13:27:59.966374
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'db9bff315424'
down_revision: Union[str, None] = '311d65e109de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entitlements', sa.Column('external_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entitlements', 'external_id')
    # ### end Alembic commands ###
